#!/bin/sh
########################################################################
# Begin mdev
#
# Description : mdev like a boss
#
# Authors     : Piotr Karbowski
#
# Version     : LFS 7.5
#
########################################################################

### BEGIN INIT INFO
# Provides:            mdev
# Required-Start:
# Should-Start:        modules
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Populates /dev with device nodes.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
   start)
      log_info_msg "Populating /dev with device nodes... "

      # Avoid race conditions, serialize hotplug events.
      touch /dev/mdev.seq

      # Some basic nodes.
      [ ! -e /dev/console ] && mknod /dev/console c 5 1
      [ ! -e /dev/null ]    && mknod /dev/null c 1 3
      [ ! -e /dev/tty ]     && mknod /dev/tty c 5 0
      [ ! -e /dev/tty1 ]    && mknod /dev/tty1 c 4 1
      [ ! -e /dev/urandom ] && mknod /dev/urandom c 1 9
      [ ! -e /dev/random ]  && mknod /dev/random c 1 8
      [ ! -e /dev/zero ]    && mknod /dev/zero c 1 5

      ln -snf /proc/self/fd /dev/fd
      ln -snf fd/0 /dev/stdin
      ln -snf fd/1 /dev/stdout
      ln -snf fd/2 /dev/stderr
      [ -e /proc/kcore ] && ln -snf /proc/kcore /dev/core

      mkdir -m 0755 /dev/pts

      # Setting up mdev as hotplug agent
      if [ -e /proc/sys/kernel/hotplug ] ; then
          echo /sbin/mdev > /proc/sys/kernel/hotplug
      fi

      # Loading kernel modules for detected hardware
      env -i /sbin/mdev -s
      # mdev -s does not poke network interfaces or usb devices so we need to do it here.
      for i in /sys/class/net/*/uevent; do printf 'add' > "$i"; done 2>/dev/null; unset i
      for i in /sys/bus/usb/devices/*; do
          case "${i##*/}" in
              [0-9]*-[0-9]*)
                  printf 'add' > "$i/uevent"
              ;;
          esac
      done; unset i
      # Load kernel modules, run twice.
      find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs modprobe -b -a 2>/dev/null
      find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs modprobe -b -a 2>/dev/null

      log_success_msg2 
      ;;

   *)
      echo "Usage ${0} {start}"
      exit 1
      ;;
esac

exit 0

# End udev
